import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Loader from "@/components/shared/Loader";
import "./globals.css";
import Header from "@/components/shared/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Bank",
  description: "Generated by Hemal Parmar",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          id="mainDiv"
          className="h-screen flex flex-col relative overflow-auto"
        >
          <Header />
          <Loader />
          <main className="flex-1">
            {children}
          </main>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
